'use client';
import { useCallback, useEffect, useMemo, useState } from 'react'; import { CalendarClock, CheckCircle2, Download, RefreshCw, Search, XCircle } from 'lucide-react'; import { API_BASE, getToken } from '@/src/lib/api'; import ClienteSelector, { ClienteCoincidencia } from '../../components/ClienteSelector';
type Promesa = any; async function api(path: string, options: RequestInit = {}) { const h = new Headers(options.headers); if (options.body) h.set('Content-Type', 'application/json'); h.set('Authorization', `Bearer ${getToken()}`); const r = await fetch(`${API_BASE}${path}`, { ...options, headers: h, cache: 'no-store' }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.message || 'Error'); return d } async function bajar(path: string, name: string) { const r = await fetch(`${API_BASE}${path}`, { headers: { Authorization: `Bearer ${getToken()}` } }); if (!r.ok) throw new Error('No se pudo generar PDF'); const u = URL.createObjectURL(await r.blob()), a = document.createElement('a'); a.href = u; a.download = name; a.click(); URL.revokeObjectURL(u) }
export default function Page() {
    const [promesas, setPromesas] = useState<Promesa[]>([]), [estado, setEstado] = useState(''), [buscar, setBuscar] = useState(''), [cliente, setCliente] = useState<ClienteCoincidencia | null>(null), [mensualidades, setMensualidades] = useState<any[]>([]), [mensualidadId, setMensualidadId] = useState(''), [fecha, setFecha] = useState(''), [obs, setObs] = useState(''), [msg, setMsg] = useState(''), [error, setError] = useState(''); const cargar = useCallback(async () => { try { const d = await api(`/promesas-pago${estado ? `?estado=${estado}` : ''}`); setPromesas(d.promesas || []) } catch (e: any) { setError(e.message) } }, [estado]); useEffect(() => { void cargar() }, [cargar]); async function seleccionar(c: ClienteCoincidencia) { setCliente(c.clienteId ? c : null); setMensualidadId(''); if (c.clienteId) { const d = await api(`/promesas-pago/mensualidades-cliente/${c.clienteId}`); setMensualidades(d.mensualidades || []) } } async function crear(e: any) { e.preventDefault(); try { await api('/promesas-pago', { method: 'POST', body: JSON.stringify({ mensualidadId, fechaPromesaPago: fecha, observacion: obs || null }) }); setMsg('Promesa creada correctamente.'); setCliente(null); setMensualidades([]); setMensualidadId(''); setFecha(''); setObs(''); await cargar() } catch (e: any) { setError(e.message) } } async function cancelar(id: string) { await api(`/promesas-pago/${id}/cancelar`, { method: 'PATCH', body: JSON.stringify({ motivo: 'Cancelada manualmente' }) }); await cargar() } const f = useMemo(() => { const q = buscar.toLowerCase(); return promesas.filter(p => `${p.nombres || ''} ${p.apellidos || ''} ${p.cedula || ''} ${p.telefono || ''} ${p.ipCliente || ''} ${p.mensualidadId || ''}`.toLowerCase().includes(q)) }, [promesas, buscar]); return <div className="space-y-6 text-slate-100">
        <div className="flex flex-col gap-4 rounded-2xl border border-slate-800 bg-slate-900/95 p-5 shadow-xl md:flex-row md:items-center md:justify-between">
            <div className="flex items-center gap-3">
                <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/10 p-3"><CalendarClock className="h-6 w-6 text-cyan-300" /></div>
                <div><h2 className="text-xl font-black text-white">Promesas de pago</h2><p className="text-sm text-slate-400">Busca al cliente por nombre, cédula, celular o ID y selecciona su mensualidad.</p></div>
            </div>
            <button onClick={() => void bajar(`/reportes-pdf-isp/promesas${estado ? `?estado=${estado}` : ''}`, 'promesas-pago.pdf')} className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 px-4 py-2 font-bold text-cyan-200 transition hover:bg-cyan-500/20"><Download className="mr-1 inline h-4 w-4" /> PDF</button>
        </div>

        {error && <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm font-medium text-red-200">{error}</div>}
        {msg && <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm font-medium text-emerald-200"><CheckCircle2 className="mr-2 inline h-4 w-4" />{msg}</div>}

        <form onSubmit={crear} className="grid gap-4 rounded-2xl border border-slate-800 bg-slate-900/95 p-5 shadow-xl md:grid-cols-4">
            <div><label className="mb-1.5 block text-sm font-semibold text-slate-300">Cliente</label><ClienteSelector value={cliente} onSelect={c => void seleccionar(c)} /></div>
            <div><label className="mb-1.5 block text-sm font-semibold text-slate-300">Mensualidad pendiente</label><select required value={mensualidadId} onChange={e => setMensualidadId(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-slate-100 outline-none transition focus:border-cyan-500"><option value="">Seleccionar</option>{mensualidades.map(m => <option key={m.mensualidadId} value={m.mensualidadId}>{m.periodo} · {m.estado} · ${Number(m.valorMensualidad || 0).toFixed(2)}</option>)}</select></div>
            <div><label className="mb-1.5 block text-sm font-semibold text-slate-300">Fecha prometida</label><input required type="date" value={fecha} onChange={e => setFecha(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-slate-100 outline-none transition focus:border-cyan-500" /></div>
            <div><label className="mb-1.5 block text-sm font-semibold text-slate-300">Observación</label><input value={obs} onChange={e => setObs(e.target.value)} placeholder="Acuerdo con el cliente" className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-slate-100 placeholder:text-slate-500 outline-none transition focus:border-cyan-500" /><button className="mt-2.5 w-full rounded-xl bg-cyan-600 px-3 py-2.5 font-bold text-white transition hover:bg-cyan-500">Crear promesa</button></div>
        </form>

        <div className="rounded-2xl border border-slate-800 bg-slate-900/95 p-5 shadow-xl">
            <div className="mb-4 flex flex-col gap-3 md:flex-row">
                <div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-500" /><input value={buscar} onChange={e => setBuscar(e.target.value)} placeholder="Nombre, cédula, celular, IP o mensualidad" className="w-full rounded-xl border border-slate-700 bg-slate-950 py-2.5 pl-9 pr-3 text-slate-100 placeholder:text-slate-500 outline-none transition focus:border-cyan-500" /></div>
                <select value={estado} onChange={e => setEstado(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-slate-100 outline-none focus:border-cyan-500"><option value="">Todos los estados</option><option>ACTIVA</option><option>CUMPLIDA</option><option>INCUMPLIDA</option><option>CANCELADA</option></select>
                <button onClick={() => void cargar()} type="button" className="rounded-xl border border-slate-700 bg-slate-800 px-3 py-2.5 text-slate-200 transition hover:bg-slate-700"><RefreshCw className="h-4 w-4" /></button>
            </div>
            <div className="overflow-x-auto">
                <table className="w-full min-w-[820px] text-sm">
                    <thead><tr className="border-b border-slate-700 text-left text-xs uppercase tracking-wide text-slate-400"><th className="px-3 py-3">Cliente</th><th className="px-3">Cédula / Celular</th><th className="px-3">Periodo</th><th className="px-3">Fecha</th><th className="px-3">Estado</th><th className="px-3 text-right">Acción</th></tr></thead>
                    <tbody>{f.map(p => <tr key={p.promesaId} className="border-b border-slate-800/80 transition hover:bg-slate-800/40"><td className="px-3 py-4 font-semibold text-white">{p.nombres} {p.apellidos}</td><td className="px-3 text-slate-300">{p.cedula || '-'}<br /><small className="text-slate-500">{p.telefono || '-'}</small></td><td className="px-3 text-slate-300">{p.periodo}</td><td className="px-3 text-slate-300">{String(p.fechaPromesaPago).slice(0, 10)}</td><td className="px-3"><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-bold ${p.estado === 'ACTIVA' ? 'border-amber-500/30 bg-amber-500/10 text-amber-300' : p.estado === 'CUMPLIDA' ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300' : p.estado === 'INCUMPLIDA' ? 'border-red-500/30 bg-red-500/10 text-red-300' : 'border-slate-600 bg-slate-800 text-slate-300'}`}>{p.estado}</span></td><td className="px-3 text-right">{p.estado === 'ACTIVA' && <button onClick={() => void cancelar(p.promesaId)} className="inline-flex items-center gap-1 rounded-lg border border-red-500/30 bg-red-500/10 px-2.5 py-1.5 font-semibold text-red-300 transition hover:bg-red-500/20"><XCircle className="h-4 w-4" /> Cancelar</button>}</td></tr>)}
                        {!f.length && <tr><td colSpan={6} className="px-3 py-10 text-center text-slate-500">No hay promesas de pago para mostrar.</td></tr>}</tbody>
                </table>
            </div>
        </div>
    </div>
}