'use client';
import {useEffect,useState} from 'react';import {API_BASE,getToken} from '@/src/lib/api';import {BookOpen,Landmark,Plus,RefreshCw,Scale,Download} from 'lucide-react';
const money=(v:any)=>new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}).format(Number(v||0));
async function api(path:string,init?:RequestInit){const r=await fetch(`${API_BASE}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${getToken()}`,...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Error contable');return d;}
export default function ContabilidadIspPage(){const now=new Date();const [tab,setTab]=useState('reportes'),[cuentas,setCuentas]=useState<any[]>([]),[periodos,setPeriodos]=useState<any[]>([]),[asientos,setAsientos]=useState<any[]>([]),[desde,setDesde]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`),[hasta,setHasta]=useState(now.toISOString().slice(0,10)),[er,setEr]=useState<any>(null),[bg,setBg]=useState<any>(null),[balance,setBalance]=useState<any[]>([]),[error,setError]=useState('');
 async function cargar(){setError('');try{const [c,p,a,e,b,bc]=await Promise.all([api('/contabilidad-isp/cuentas'),api('/contabilidad-isp/periodos'),api('/contabilidad-isp/asientos'),api(`/contabilidad-isp/reportes/estado-resultados?desde=${desde}&hasta=${hasta}`),api(`/contabilidad-isp/reportes/balance-general?desde=${desde}&hasta=${hasta}`),api(`/contabilidad-isp/reportes/balance-comprobacion?desde=${desde}&hasta=${hasta}`)]);setCuentas(c.cuentas||[]);setPeriodos(p.periodos||[]);setAsientos(a.asientos||[]);setEr(e);setBg(b);setBalance(bc.cuentas||[])}catch(e:any){setError(e.message)}} useEffect(()=>{cargar()},[desde,hasta]);
 async function sincronizarHistorico(){try{setError('');await api('/contabilidad-isp/sincronizar-historico',{method:'POST'});await cargar()}catch(e:any){setError(e.message)}}
 async function descargarPdf(){try{const r=await fetch(`${API_BASE}/reportes-pdf-isp/contabilidad?desde=${desde}&hasta=${hasta}`,{headers:{Authorization:`Bearer ${getToken()}`}});if(!r.ok)throw new Error('No se pudo generar PDF');const u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download=`contabilidad-${desde}-${hasta}.pdf`;a.click();URL.revokeObjectURL(u)}catch(e:any){setError(e.message)}}
 const [nueva,setNueva]=useState({codigo:'',nombre:'',tipo:'ACTIVO',naturaleza:'DEUDORA'});async function crearCuenta(){try{await api('/contabilidad-isp/cuentas',{method:'POST',body:JSON.stringify(nueva)});setNueva({codigo:'',nombre:'',tipo:'ACTIVO',naturaleza:'DEUDORA'});cargar()}catch(e:any){setError(e.message)}}
 return <div className="space-y-5 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">Contabilidad ISP</h2><p className="text-sm text-slate-400">Partida doble, períodos y estados financieros.</p></div><div className="flex gap-2"><input type="date" value={desde} onChange={e=>setDesde(e.target.value)} className="rounded-xl bg-slate-900 border border-slate-700 px-3 py-2"/><input type="date" value={hasta} onChange={e=>setHasta(e.target.value)} className="rounded-xl bg-slate-900 border border-slate-700 px-3 py-2"/><button onClick={()=>void sincronizarHistorico()} className="rounded-xl border border-emerald-500/40 px-3 text-sm font-bold">Sincronizar</button><button onClick={()=>void descargarPdf()} className="rounded-xl border border-cyan-500/40 px-3"><Download className="h-4 w-4"/></button><button onClick={cargar} className="rounded-xl bg-cyan-600 px-3"><RefreshCw className="h-4 w-4"/></button></div></div>{error&&<div className="rounded-xl bg-red-500/10 border border-red-500/30 p-3 text-red-200">{error}</div>}
 <div className="flex flex-wrap gap-2">{[['reportes','Reportes'],['cuentas','Plan de cuentas'],['asientos','Asientos'],['periodos','Períodos']].map(([k,n])=><button key={k} onClick={()=>setTab(k)} className={`rounded-xl px-4 py-2 font-bold ${tab===k?'bg-cyan-600':'bg-slate-900 border border-slate-700'}`}>{n}</button>)}</div>
 {tab==='reportes'&&<><div className="grid gap-4 md:grid-cols-4">{[['Ingresos',er?.ingresos],['Gastos',Number(er?.gastos||0)+Number(er?.costos||0)],['Utilidad',er?.utilidad],['Activos',bg?.activos]].map(([n,v])=><div key={String(n)} className="rounded-2xl bg-slate-900 border border-cyan-500/20 p-4"><Scale className="h-5 w-5 text-cyan-300"/><p className="mt-3 text-xs text-slate-400">{n}</p><b className="text-xl">{money(v)}</b></div>)}</div><section className="rounded-2xl bg-slate-900 border border-slate-800 p-5 overflow-x-auto"><h3 className="font-black mb-3">Balance de comprobación</h3><table className="w-full text-sm"><thead><tr className="text-left text-slate-400"><th>Código</th><th>Cuenta</th><th>Debe</th><th>Haber</th><th>Saldo</th></tr></thead><tbody>{balance.map((r:any)=><tr key={r.codigo} className="border-t border-slate-800"><td className="py-3">{r.codigo}</td><td>{r.nombre}</td><td>{money(r.debe)}</td><td>{money(r.haber)}</td><td>{money(r.saldo)}</td></tr>)}</tbody></table></section></>}
 {tab==='cuentas'&&<section className="space-y-4"><div className="grid gap-2 rounded-2xl bg-slate-900 border border-slate-800 p-4 md:grid-cols-5"><input placeholder="Código" value={nueva.codigo} onChange={e=>setNueva({...nueva,codigo:e.target.value})} className="rounded-xl bg-slate-950 border border-slate-700 px-3 py-2"/><input placeholder="Nombre" value={nueva.nombre} onChange={e=>setNueva({...nueva,nombre:e.target.value})} className="rounded-xl bg-slate-950 border border-slate-700 px-3 py-2"/><select value={nueva.tipo} onChange={e=>setNueva({...nueva,tipo:e.target.value})} className="rounded-xl bg-slate-950 border border-slate-700 px-3">{['ACTIVO','PASIVO','PATRIMONIO','INGRESO','GASTO','COSTO'].map(x=><option key={x}>{x}</option>)}</select><select value={nueva.naturaleza} onChange={e=>setNueva({...nueva,naturaleza:e.target.value})} className="rounded-xl bg-slate-950 border border-slate-700 px-3"><option>DEUDORA</option><option>ACREEDORA</option></select><button onClick={crearCuenta} className="rounded-xl bg-emerald-600 font-bold"><Plus className="inline h-4 w-4"/> Crear</button></div><div className="rounded-2xl bg-slate-900 border border-slate-800 p-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-400"><th>Código</th><th>Nombre</th><th>Tipo</th><th>Naturaleza</th><th>Estado</th></tr></thead><tbody>{cuentas.map((c:any)=><tr key={c.cuentaId} className="border-t border-slate-800"><td className="py-3">{c.codigo}</td><td>{c.nombre}</td><td>{c.tipo}</td><td>{c.naturaleza}</td><td>{c.estado}</td></tr>)}</tbody></table></div></section>}
 {tab==='asientos'&&<div className="rounded-2xl bg-slate-900 border border-slate-800 p-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-400"><th>Fecha</th><th>Número</th><th>Concepto</th><th>Debe</th><th>Haber</th><th>Estado</th></tr></thead><tbody>{asientos.map((a:any)=><tr key={a.asientoId} className="border-t border-slate-800"><td className="py-3">{String(a.fecha).slice(0,10)}</td><td>{a.numero}</td><td>{a.concepto}</td><td>{money(a.totalDebe)}</td><td>{money(a.totalHaber)}</td><td>{a.estado}</td></tr>)}</tbody></table></div>}
 {tab==='periodos'&&<div className="grid gap-3 md:grid-cols-3">{periodos.map((p:any)=><div key={p.periodoId} className="rounded-2xl bg-slate-900 border border-slate-800 p-4"><BookOpen className="h-5 w-5 text-cyan-300"/><b className="mt-2 block text-lg">{p.periodo}</b><span className="text-sm text-slate-400">{p.estado}</span></div>)}</div>}
 </div>}
